### ISSUE TITLE
parts of stack trace missing when promise rejects

### ISSUE THREAD

**Issue by SimonSiefke** [sindresorhus/p-timeout#32]
When passing a promise to pTimeout that rejects, `error.stack` ends at `p-timeout/index.js:92:13`

Example 1: 

```js
import pTimeout from "p-timeout";
import { setTimeout } from "node:timers/promises";

const a = async () => {
  await setTimeout(1);
  throw new Error("oops");
};

const b = async () => {
  await pTimeout(a(), { milliseconds: 500 });
};

try {
  await b();
} catch (error) {
  console.log(error.stack);
}

```

Example 1 output: 

```
Error: oops
    at a (file:///tmp/index.js:6:9)
    at async file:///tmp/node_modules/p-timeout/index.js:92:13
```

<br>
<br>

Example 2:

```js
import { setTimeout } from "node:timers/promises";

const a = async () => {
  await setTimeout(1);
  throw new Error("oops");
};

const b = async () => {
  await a();
};

try {
  await b();
} catch (error) {
  console.log(error.stack);
}

```

Example 2 output:

```
Error: oops
    at a (file:///tmp/index.js:6:9)
    at async b (file:///tmp/indexjs:10:3)
    at async file:///tmp/index.js:14:3
```

<br>

In Example 1, these parts are missing from `error.stack`: 

```
   at async b (file:///tmp/index.js:10:3)
   at async file:///tmp/index.js:14:3
```

**Comment by sindresorhus** [comment]
It's because of the async-IIFE: https://github.com/sindresorhus/p-timeout/blob/200df030078d8fdf57d005f798bed5a719ed7618/index.js#L90

This is really just a limitation in JavaScript engines: https://stackoverflow.com/a/68081429/64949

**Comment by silverwind** [comment]
I suppose you could just remove the IIFE and make the parent function `async`.

**Comment by Sadegh-bj** [comment]
> When passing a promise to pTimeout that rejects, `error.stack` ends at `p-timeout/index.js:92:13`
> 
> 
> 
> Example 1: 
> 
> 
> 
> ```js
> 
> import pTimeout from "p-timeout";
> 
> import { setTimeout } from "node:timers/promises";
> 
> 
> 
> const a = async () => {
> 
>   await setTimeout(1);
> 
>   throw new Error("oops");
> 
> };
> 
> 
> 
> const b = async () => {
> 
>   await pTimeout(a(), { milliseconds: 500 });
> 
> };
> 
> 
> 
> try {
> 
>   await b();
> 
> } catch (error) {
> 
>   console.log(error.stack);
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> Example 1 output: 
> 
> 
> 
> ```
> 
> Error: oops
> 
>     at a (file:///tmp/index.js:6:9)
> 
>     at async file:///tmp/node_modules/p-timeout/index.js:92:13
> 
> ```
> 
> 
> 
> <br>
> 
> <br>
> 
> 
> 
> Example 2:
> 
> 
> 
> ```js
> 
> import { setTimeout } from "node:timers/promises";
> 
> 
> 
> const a = async () => {
> 
>   await setTimeout(1);
> 
>   throw new Error("oops");
> 
> };
> 
> 
> 
> const b = async () => {
> 
>   await a();
> 
> };
> 
> 
> 
> try {
> 
>   await b();
> 
> } catch (error) {
> 
>   console.log(error.stack);
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> Example 2 output:
> 
> 
> 
> ```
> 
> Error: oops
> 
>     at a (file:///tmp/index.js:6:9)
> 
>     at async b (file:///tmp/indexjs:10:3)
> 
>     at async file:///tmp/index.js:14:3
> 
> ```
> 
> 
> 
> <br>
> 
> 
> 
> In Example 1, these parts are missing from `error.stack`: 
> 
> 
> 
> ```
> 
>    at async b (file:///tmp/index.js:10:3)
> 
>    at async file:///tmp/index.js:14:3
> 
> ```
